const posts = [
  {
    id: 1,
    type: "publication",
    user: {
      id: 69,
      profile_pic: "",
      name: "Elon Musk",
    },
    title: "Hello World!",
    text: "Hello World!",
    commentsCount: 10,
    isLiked: false,
    likesCount: 1234,
    created_at: "2021-09-01T12:00:00.000Z",
  },
  {
    id: 2,
    type: "poll",
    user: {
      id: 69,
      profile_pic: "example.com/image.jpg",
      name: "Elon Musk",
    },
    question: "What is your favorite color?",
    options: [
      {
        id: 1,
        text: "Red",
        votes: 69,
      },
      {
        id: 2,
        text: "Blue",
        votes: 420,
      },
      {
        id: 3,
        text: "Green",
        votes: 1337,
      },
    ],
    commentsCount: 69,
    isLiked: false,
    likesCount: 1234,
    created_at: "2021-09-01T12:00:00.000Z",
  },
];

export const data: FeedItemProps[] = [
  {
    id: 1,
    type: "publication",
    user: {
      id: "69",
      profile_pic: "example.com/image.jpg",
      name: "Elon Musk",
    },
    question: "What is your favorite color?",
    options: [
      {
        id: 1,
        text: "Red",
        votes: 69,
      },
    ],
    votedOptionId: 1,
    commentsCount: 69,
    isLiked: false,
    likesCount: 1234,
    created_at: "2021-09-01T12:00:00.000Z",
    text: "Ayo what the fuck ?",
  },
  {
    id: 2,
    type: "publication",
    user: {
      id: "80",
      profile_pic: "",
      name: "Elon Husk",
    },
    title: "Hello World!",
    text: "Hello World!",
    image: "",
    commentsCount: 10,
    isLiked: false,
    likesCount: 1234,
    created_at: "2021-09-01T12:00:00.000Z",
    question: "",
    options: [],
  },
  {
    id: 3,
    type: "poll",
    user: {
      id: "69",
      profile_pic: "example.com/image.jpg",
      name: "Elon Musk",
    },
    question: "What is your favorite color?",
    options: [
      {
        id: 1,
        text: "Red",
        votes: 69,
      },
      {
        id: 2,
        text: "Blue",
        votes: 420,
      },
      {
        id: 3,
        text: "Green",
        votes: 1337,
      },
    ],
    commentsCount: 69,
    isLiked: false,
    likesCount: 1234,
    created_at: "2021-09-01T12:00:00.000Z",
    text: "",
  },
  {
    id: 4,
    type: "publication",
    user: {
      id: "42",
      profile_pic: "example.com/profile_pic_42.jpg",
      name: "Jane Doe",
    },
    title: "My trip to Paris",
    text: "Last month, I had the chance to travel to Paris for the first time. It was an amazing experience and I got to see so many beautiful things!",
    image: "example.com/paris.jpg",
    commentsCount: 27,
    isLiked: true,
    likesCount: 132,
    created_at: "2023-04-25T10:30:00.000Z",
    question: "",
    options: [],
  },
  {
    id: 5,
    type: "poll",
    user: {
      id: "27",
      profile_pic: "example.com/profile_pic_27.jpg",
      name: "John Smith",
    },
    question: "What is your favorite programming language?",
    options: [
      {
        id: 1,
        text: "JavaScript",
        votes: 35,
      },
      {
        id: 2,
        text: "Python",
        votes: 27,
      },
      {
        id: 3,
        text: "Java",
        votes: 18,
      },
      {
        id: 4,
        text: "C++",
        votes: 14,
      },
      {
        id: 5,
        text: "Other",
        votes: 6,
      },
    ],
    commentsCount: 13,
    isLiked: false,
    likesCount: 98,
    created_at: "2023-05-02T14:20:00.000Z",
    text: "",
    votedOptionId: 2,
  },
  {
    id: 6,
    type: "publication",
    user: {
      id: "42",
      profile_pic: "",
      name: "Ada Lovelace",
    },
    title: "The Analytical Engine",
    text: "I'm working on a new machine, which, if successful, will have far-reaching consequences on society.",
    image: "",
    commentsCount: 3,
    isLiked: false,
    likesCount: 42,
    created_at: "2021-09-04T09:00:00.000Z",
    question: "",
    options: [],
  },
  {
    id: 7,
    type: "poll",
    user: {
      id: "23",
      profile_pic: "example.com/user23.jpg",
      name: "Grace Hopper",
    },
    question: "Which programming language do you prefer?",
    options: [
      {
        id: 1,
        text: "Python",
        votes: 25,
      },
      {
        id: 2,
        text: "JavaScript",
        votes: 50,
      },
      {
        id: 3,
        text: "Java",
        votes: 30,
      },
      {
        id: 4,
        text: "C++",
        votes: 20,
      },
    ],
    commentsCount: 15,
    isLiked: true,
    likesCount: 75,
    created_at: "2021-09-03T15:00:00.000Z",
    text: "",
  },
  {
    id: 8,
    type: "publication",
    user: {
      id: "69",
      profile_pic: "",
      name: "Elon Musk",
    },
    title: "Going to Mars",
    text: "We're going to establish a human colony on Mars within the next decade.",
    image: "example.com/mars.jpg",
    commentsCount: 50,
    isLiked: false,
    likesCount: 500,
    created_at: "2021-09-02T18:00:00.000Z",
    question: "",
    options: [],
  },
  {
    id: 9,
    type: "poll",
    user: {
      id: "23",
      profile_pic: "example.com/user23.jpg",
      name: "Grace Hopper",
    },
    question: "Which operating system do you use?",
    options: [
      {
        id: 1,
        text: "Windows",
        votes: 40,
      },
      {
        id: 2,
        text: "macOS",
        votes: 30,
      },
      {
        id: 3,
        text: "Linux",
        votes: 20,
      },
      {
        id: 4,
        text: "Other",
        votes: 10,
      },
    ],
    commentsCount: 10,
    isLiked: true,
    likesCount: 75,
    created_at: "2021-09-05T12:00:00.000Z",
    text: "",
  },
];
